# Generated by Django 2.2.17 on 2021-01-21 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_acive',
            new_name='is_active',
        ),
    ]
