# Generated by Django 2.2.17 on 2021-01-17 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20210117_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender_no_choice',
            field=models.CharField(blank=True, max_length=20, verbose_name='пол без выбора'),
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 14, 45, 9, 384188, tzinfo=utc)),
        ),
    ]
